# Generated by Django 4.1 on 2022-08-31 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='Avarage_review_rating',
            new_name='Average_review_rating',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='Num_of_enrolles_student',
            new_name='Num_of_enrolled_students',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='qualification',
            new_name='Qualification',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='User',
            new_name='user',
        ),
    ]
