# Generated by Django 4.1 on 2022-09-06 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_rename_avarage_review_rating_registration_average_review_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='Couse_fee',
            new_name='Course_fee',
        ),
    ]
