# Generated by Django 4.1 on 2022-09-12 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_rename_couse_fee_subject_course_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learning_progress',
            old_name='Course_Chapter_Content_name',
            new_name='Course_chapter_content_name',
        ),
        migrations.RenameField(
            model_name='learning_progress',
            old_name='Course_Chapter_name',
            new_name='Course_chapter_name',
        ),
    ]
