# Generated by Django 4.1 on 2022-09-14 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0005_rename_chapter_text_content_subject_chapter_text_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='Email',
        ),
    ]
